import type { DetectionMarker, AuditRecord, EvidenceMatrixRow, GeminiExplanation, CapturedPhotos } from '@/types/evidence';

// High-fidelity wheat sample imagery (Unsplash high quality real agricultural photography)
export const DEMO_PHOTOS: CapturedPhotos = {
  main: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=1200&q=80',
  closeUp: 'https://images.unsplash.com/photo-1543257580-7269da773bf5?auto=format&fit=crop&w=1200&q=80',
  context: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1200&q=80',
};

export const DEMO_WHEAT_DETECTIONS: DetectionMarker[] = [
  {
    id: 1,
    category: 'foreign_object',
    categoryLabel: 'Foreign Material (Inorganic Gravel)',
    status: 'OBSERVED',
    confidence: 0.98,
    xPercent: 28.5,
    yPercent: 34.2,
    widthPercent: 4.2,
    heightPercent: 4.8,
    findingTitle: 'Foreign Material: Silica / Stone Fragment',
    visualEvidence: 'Dark crystalline, non-organic angular fragment with 0% grain contour agreement. High optical density and sharp edge reflectance.',
    visualReasoning: 'Contrast differential exceeding 75% compared to baseline wheat grain matrix. Geometry exhibits jagged non-biological cleavage planes.',
    estimatedSizeMm: 3.4,
    isHighPriorityAnomaly: true,
    colorHex: '#DC2626',
    photoSource: 'main',
  },
  {
    id: 2,
    category: 'foreign_object',
    categoryLabel: 'Foreign Material (Wild Weed Seed)',
    status: 'OBSERVED',
    confidence: 0.94,
    xPercent: 72.1,
    yPercent: 61.8,
    widthPercent: 3.5,
    heightPercent: 3.8,
    findingTitle: 'Foreign Material: Wild Black Weed Seed Candidate',
    visualEvidence: 'Small spherical black botanical seed (approx. 2.1mm) with micro-punctate seed coat distinct from wheat kernel anatomy.',
    visualReasoning: 'Spherical aspect ratio (0.95) and deep melanin pigmentation indicate adventitious weed admixture (e.g. Wild Oat / Black Grass).',
    estimatedSizeMm: 2.1,
    isHighPriorityAnomaly: true,
    colorHex: '#DC2626',
    photoSource: 'closeUp',
  },
  {
    id: 3,
    category: 'broken_grain',
    categoryLabel: 'Broken / Damaged Grain',
    status: 'OBSERVED',
    confidence: 0.96,
    xPercent: 45.2,
    yPercent: 22.4,
    widthPercent: 3.8,
    heightPercent: 3.2,
    findingTitle: 'Broken Grain: Transverse Endosperm Cleavage',
    visualEvidence: 'Grain truncated at mid-section with exposed chalky starchy endosperm. Missing distal brush end.',
    visualReasoning: 'Length-to-width ratio of 1.15 vs standard 2.45 for intact wheat. Irregular fracture line with high chalk reflectance.',
    estimatedSizeMm: 3.2,
    isHighPriorityAnomaly: true,
    colorHex: '#D97706',
    photoSource: 'main',
  },
  {
    id: 4,
    category: 'broken_grain',
    categoryLabel: 'Broken / Damaged Grain',
    status: 'OBSERVED',
    confidence: 0.92,
    xPercent: 63.8,
    yPercent: 41.5,
    widthPercent: 3.4,
    heightPercent: 3.0,
    findingTitle: 'Broken Grain: Embryo Tip Fracture',
    visualEvidence: 'Germ end sheared off cleanly with exposed sub-aleurone tissue.',
    visualReasoning: 'Asymmetric contour loss corresponding to mechanical threshing damage.',
    estimatedSizeMm: 4.1,
    isHighPriorityAnomaly: true,
    colorHex: '#D97706',
    photoSource: 'closeUp',
  },
  {
    id: 5,
    category: 'discolored_shriveled',
    categoryLabel: 'Visible Discoloration / Shriveled Kernel',
    status: 'OBSERVED',
    confidence: 0.89,
    xPercent: 38.0,
    yPercent: 55.6,
    widthPercent: 3.2,
    heightPercent: 4.5,
    findingTitle: 'Discolored / Shriveled Kernel',
    visualEvidence: 'Deep longitudinal wrinkles across pericarp with dull gray-brown hue (L* value 38 vs 62 normal).',
    visualReasoning: 'Thermal stress / premature desiccation pattern. Surface convolution depth exceeds 0.4mm.',
    estimatedSizeMm: 4.8,
    isHighPriorityAnomaly: true,
    colorHex: '#C2410C',
    photoSource: 'main',
  },
  {
    id: 6,
    category: 'visible_physical_damage',
    categoryLabel: 'Physical Surface Damage',
    status: 'OBSERVED',
    confidence: 0.87,
    xPercent: 52.4,
    yPercent: 78.1,
    widthPercent: 3.6,
    heightPercent: 3.9,
    findingTitle: 'Physical Surface Abrasion',
    visualEvidence: 'Pericarp abrasion and micro-scratches on dorsal curve with localized loss of bran gloss.',
    visualReasoning: 'Frictional wear pattern consistent with high-velocity mechanical auger transfer.',
    estimatedSizeMm: 5.6,
    isHighPriorityAnomaly: true,
    colorHex: '#B45309',
    photoSource: 'main',
  },
  {
    id: 7,
    category: 'abnormal_appearance',
    categoryLabel: 'Abnormal Appearance (Cavity Aperture)',
    status: 'POSSIBLE',
    confidence: 0.84,
    xPercent: 18.2,
    yPercent: 67.4,
    widthPercent: 3.1,
    heightPercent: 3.4,
    findingTitle: 'Abnormal Surface Cavity / Possible Insect Bore',
    visualEvidence: 'Circular dark aperture (approx. 0.8mm) with internal optical shadowing on lateral flank.',
    visualReasoning: '2D optical shadow suggests cavity depth. External photography cannot confirm if cavity penetrates full kernel without manual probe.',
    estimatedSizeMm: 5.2,
    isHighPriorityAnomaly: true,
    colorHex: '#B45309',
    photoSource: 'main',
  },
];

export const DEMO_WHEAT_MATRIX_ROWS: EvidenceMatrixRow[] = [
  // 1. OBSERVED VISUAL EVIDENCE
  {
    id: 'mat-1',
    parameter: 'Broken / Damaged Material',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '6.4% (26 items observed)',
    status: 'OBSERVED',
    method: '2D Pixel Geometry & Cleavage Contour Analysis',
    confidence: 'High',
    note: 'Grains exhibiting cleaved endosperm or sheared germ ends visible in captured photos.',
  },
  {
    id: 'mat-2',
    parameter: 'Visible Foreign Material',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '2 items detected (0.5%)',
    status: 'OBSERVED',
    method: 'Spectral & Geometric Contrast Differential',
    confidence: 'High',
    note: '1 inorganic stone fragment (3.4mm) and 1 wild black weed seed (2.1mm) flagged.',
  },
  {
    id: 'mat-3',
    parameter: 'Visible Discoloration',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '1.8% (7 items observed)',
    status: 'OBSERVED',
    method: 'Pericarp Chromatic Dispersion',
    confidence: 'High',
    note: 'Shriveled and dull gray-brown kernels distinct from standard golden baseline.',
  },
  {
    id: 'mat-4',
    parameter: 'Physical Surface Damage',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '1.2% (5 items observed)',
    status: 'OBSERVED',
    method: 'Surface Texture & Abrasion Detection',
    confidence: 'Medium',
    note: 'Dorsal abrasions and mechanical friction marks on grain pericarp.',
  },
  {
    id: 'mat-5',
    parameter: 'Abnormal Visual Appearance',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '1 candidate observed (Cavity aperture)',
    status: 'POSSIBLE',
    method: '2D Aperture Shadowing',
    confidence: 'Medium',
    note: 'Surface bore aperture visible; internal verification requires manual probe.',
  },
  {
    id: 'mat-6',
    parameter: 'Capture Quality Gate Status',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: 'PASSED (96% Quality Score)',
    status: 'OBSERVED',
    method: '8-Parameter Pre-Validation CV Pipeline',
    confidence: 'High',
    note: 'Passed sharpness, lighting, framing, glare, shadow, and visibility checks.',
  },

  // 2. UNVERIFIED LABORATORY MEASUREMENTS
  {
    id: 'mat-unver-1',
    parameter: 'Moisture Percentage',
    categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
    result: 'Not tested (Requires certified dielectric moisture meter)',
    status: 'UNVERIFIED',
    method: 'N/A — Not Accessible via Smartphone Photography',
    confidence: 'N/A',
    note: 'KisanDrishti does not test chemical moisture. Do not infer moisture from visual color alone.',
  },
  {
    id: 'mat-unver-2',
    parameter: 'Protein / Gluten Content',
    categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
    result: 'Not tested (Requires NIR spectrometer or Kjeldahl chemical titration)',
    status: 'UNVERIFIED',
    method: 'N/A — Requires Laboratory Equipment',
    confidence: 'N/A',
    note: 'Biochemical protein cannot be derived from 2D smartphone images.',
  },
  {
    id: 'mat-unver-3',
    parameter: 'Chemical / Pesticide Residue',
    categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
    result: 'Not tested (Requires Chromatography / Mass Spectrometry)',
    status: 'UNVERIFIED',
    method: 'N/A — Requires Chemical Assay',
    confidence: 'N/A',
    note: 'Invisible micro-contaminants cannot be visually verified.',
  },
  {
    id: 'mat-unver-4',
    parameter: 'Internal Kernel Defects',
    categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
    result: 'Not verified (Requires X-ray or destructive slicing)',
    status: 'UNVERIFIED',
    method: 'N/A — Surface Photography Only',
    confidence: 'N/A',
    note: 'Surface observations do not prove absence of internal hidden larval development.',
  },
  {
    id: 'mat-unver-5',
    parameter: 'Nutritional Values / Oil Content',
    categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
    result: 'Not tested (Requires solvent extraction)',
    status: 'UNVERIFIED',
    method: 'N/A',
    confidence: 'N/A',
    note: 'Nutritional content is outside the scope of optical visual evidence.',
  },
  {
    id: 'mat-unver-6',
    parameter: 'Final Price / Rupee Deduction',
    categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
    result: 'NOT CALCULATED (KisanDrishti does not decide value)',
    status: 'UNVERIFIED',
    method: 'N/A — Commercial Mandate',
    confidence: 'N/A',
    note: 'KisanDrishti does not calculate price cuts or enforce trade deductions.',
  },
];

export const DEMO_WHEAT_EXPLANATIONS: GeminiExplanation[] = [
  {
    finding: 'Foreign Material: Inorganic Silica Fragment (#1)',
    visualEvidence: 'Non-grain angular dark silhouette at coordinates (28.5%, 34.2%). Zero agreement with biological seed pericarp geometry.',
    visualReasoning: 'High optical density with sharp cleavage planes. Pixel intensity variance across RGB channels indicates non-organic crystalline mineral matter.',
    status: 'OBSERVED VISUAL EVIDENCE',
    limitation: 'Identifies surface foreign object in the captured sample only. Does not quantify total bulk foreign matter by weight across the entire truckload.',
    markerId: 1,
  },
  {
    finding: 'Transverse Endosperm Cleavage in Broken Grain (#3)',
    visualEvidence: 'Truncated grain contour with exposed white starchy endosperm at coordinates (45.2%, 22.4%). Distal brush end missing.',
    visualReasoning: 'Length-to-width ratio of 1.15 is significantly below standard intact wheat kernel morphology (2.45). High specular reflectance from fractured starch granules.',
    status: 'OBSERVED VISUAL EVIDENCE',
    limitation: 'Describes observable 2D surface fragmentation. Does not measure internal micro-fissuring.',
    markerId: 3,
  },
  {
    finding: 'Visible Discoloration & Thermal Desiccation (#5)',
    visualEvidence: 'Deep longitudinal wrinkles and dull gray-brown hue at coordinates (38.0%, 55.6%).',
    visualReasoning: 'L* luminosity value is 38 (normal baseline 62). Wrinkle convolution frequency indicates thermal stress during maturation.',
    status: 'OBSERVED VISUAL EVIDENCE',
    limitation: 'Visual discoloration only. Does not measure grain hardness or baking quality.',
    markerId: 5,
  },
  {
    finding: 'Abnormal Appearance: Possible Bore Aperture (#7)',
    visualEvidence: 'Circular dark aperture (approx. 0.8mm) with internal shadowing at coordinates (18.2%, 67.4%).',
    visualReasoning: '2D optical shadow suggests cavity depth. Classified as POSSIBLE because external optics cannot verify if cavity penetrates the full endosperm without destructive slicing.',
    status: 'POSSIBLE INTERPRETATION',
    limitation: 'Requires manual probe or physical inspection to confirm whether active larvae exist inside.',
    markerId: 7,
  },
];

export const DEMO_WHEAT_AUDIT: AuditRecord = {
  id: 'EVD-2026-WHT-0891',
  metadata: {
    auditId: 'EVD-2026-WHT-0891',
    lotId: 'LOT-PB-2026-0891',
    crop: 'Wheat',
    variety: 'HD-3086 (Pusa Gautami)',
    location: 'Khanna Mandi, Block B, Punjab',
    buyerRef: 'Traders Union Khanna / Lot #44',
    sampleDescription: 'Random grab sample from center and edges of trolley',
    captureTimestamp: '2026-09-13T09:42:00.000Z',
    deviceInfo: 'Standard Smartphone Camera (12MP, f/1.8)',
    sessionToken: 'sess_live_9921a8b',
    analysisVersion: 'KisanDrishti Hybrid CV + Gemini v3.2',
    hasOptionalSheetUsed: true,
  },
  imageUrl: DEMO_PHOTOS.main,
  photos: DEMO_PHOTOS,
  stats: {
    brokenPercent: 6.4,
    brokenCount: 26,
    discoloredPercent: 1.8,
    discoloredCount: 7,
    foreignObjectCount: 2,
    foreignObjectPercent: 0.5,
    visibleDamagePercent: 1.2,
    visibleDamageCount: 5,
    abnormalAppearanceCount: 1,
    sampleCoveragePercent: 94,
    captureQualityScore: 96,
    approximateAverageLengthMm: 6.8,
    opticalColorDistribution: 'Amber Golden (580nm) — 91% Optical Uniformity',
    totalObjects: 412,
    totalFlaggedObservations: 7,
    soundGrainRatePercent: 90.1,
  },
  detections: DEMO_WHEAT_DETECTIONS,
  matrixRows: DEMO_WHEAT_MATRIX_ROWS,
  explanations: DEMO_WHEAT_EXPLANATIONS,
  cryptographicHash: 'a8b7c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8',
  isDemo: true,
  isConfidenceSufficient: true,
  shareCount: 4,
  verifiedAt: '2026-09-13T09:45:12.000Z',
};

export const INITIAL_AUDIT_HISTORY: AuditRecord[] = [
  DEMO_WHEAT_AUDIT,
  {
    id: 'EVD-2026-RIC-0904',
    metadata: {
      auditId: 'EVD-2026-RIC-0904',
      lotId: 'LOT-HR-2026-0904',
      crop: 'Paddy (Rice)',
      variety: 'Basmati 1509',
      location: 'Karnal Grain Mandi, Yard #2, Haryana',
      buyerRef: 'Aggarwal Rice Mills Ltd.',
      sampleDescription: 'Sample drawn from 5 bags per 100 bags',
      captureTimestamp: '2026-09-12T14:15:00.000Z',
      deviceInfo: 'Standard Smartphone (12MP)',
      sessionToken: 'sess_live_1092a7c',
      analysisVersion: 'KisanDrishti Hybrid CV + Gemini v3.2',
      hasOptionalSheetUsed: false,
    },
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=80',
    photos: {
      main: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=80',
      closeUp: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=1200&q=80',
    },
    stats: {
      brokenPercent: 4.8,
      brokenCount: 18,
      discoloredPercent: 1.1,
      discoloredCount: 4,
      foreignObjectCount: 1,
      foreignObjectPercent: 0.3,
      visibleDamagePercent: 0.9,
      visibleDamageCount: 3,
      abnormalAppearanceCount: 0,
      sampleCoveragePercent: 96,
      captureQualityScore: 98,
      approximateAverageLengthMm: 8.4,
      opticalColorDistribution: 'Pearly Translucent — 93% Optical Uniformity',
      totalObjects: 380,
      totalFlaggedObservations: 4,
      soundGrainRatePercent: 92.9,
    },
    detections: [
      {
        id: 1,
        category: 'broken_grain',
        categoryLabel: 'Broken Basmati Tip',
        status: 'OBSERVED',
        confidence: 0.97,
        xPercent: 32.4,
        yPercent: 44.1,
        widthPercent: 3.2,
        heightPercent: 2.8,
        findingTitle: 'Broken Basmati: Longitudinal Cleavage',
        visualEvidence: 'Basmati grain cleaved longitudinally with sharp fracture line.',
        visualReasoning: 'Transverse ratio 1.2 vs 3.8 expected for intact long-grain Basmati.',
        estimatedSizeMm: 4.2,
        isHighPriorityAnomaly: true,
        colorHex: '#D97706',
        photoSource: 'main',
      },
      {
        id: 2,
        category: 'foreign_object',
        categoryLabel: 'Foreign Material (Husk Fragment)',
        status: 'OBSERVED',
        confidence: 0.91,
        xPercent: 68.2,
        yPercent: 28.6,
        widthPercent: 4.1,
        heightPercent: 3.5,
        findingTitle: 'Foreign Material: Detached Lemma Husk',
        visualEvidence: 'Cellulose husk sheath detached from grain endosperm.',
        visualReasoning: 'Fibrous hollow morphology distinct from milled rice kernel.',
        estimatedSizeMm: 3.8,
        isHighPriorityAnomaly: true,
        colorHex: '#DC2626',
        photoSource: 'main',
      },
    ],
    matrixRows: [
      {
        id: 'mat-1',
        parameter: 'Broken / Damaged Material',
        categoryGroup: 'OBSERVED VISUAL EVIDENCE',
        result: '4.8% (18 items observed)',
        status: 'OBSERVED',
        method: '2D Pixel Geometry Analysis',
        confidence: 'High',
        note: 'Grains exhibiting cleaved endosperm visible in captured photos.',
      },
      {
        id: 'mat-2',
        parameter: 'Visible Foreign Material',
        categoryGroup: 'OBSERVED VISUAL EVIDENCE',
        result: '1 item detected (0.3%)',
        status: 'OBSERVED',
        method: 'Spectral Differential',
        confidence: 'High',
        note: 'Detached lemma husk fragment.',
      },
      {
        id: 'mat-unver-1',
        parameter: 'Moisture Percentage',
        categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
        result: 'Not tested (Requires certified moisture meter)',
        status: 'UNVERIFIED',
        method: 'N/A',
        confidence: 'N/A',
        note: 'KisanDrishti does not test moisture.',
      },
    ],
    explanations: [
      {
        finding: 'Broken Basmati Grain Cleavage (#1)',
        visualEvidence: 'Basmati grain fractured at coordinates (32.4%, 44.1%).',
        visualReasoning: 'Length 4.2mm vs 8.4mm baseline. Cleavage surface shows exposed starchy core.',
        status: 'OBSERVED VISUAL EVIDENCE',
        limitation: 'Observable 2D fracture in captured sample.',
        markerId: 1,
      },
    ],
    cryptographicHash: 'f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3',
    isDemo: true,
    isConfidenceSufficient: true,
    shareCount: 2,
    verifiedAt: '2026-09-12T14:18:00.000Z',
  },
  {
    id: 'EVD-2026-MUS-0918',
    metadata: {
      auditId: 'EVD-2026-MUS-0918',
      lotId: 'LOT-RJ-2026-0918',
      crop: 'Mustard',
      variety: 'RH-749',
      location: 'Alwar Mandi, Rajasthan',
      buyerRef: 'Shri Ram Mustard Expellers',
      sampleDescription: 'Handful taken from 3 different bags',
      captureTimestamp: '2026-09-11T11:30:00.000Z',
      deviceInfo: 'Standard Smartphone (12MP)',
      sessionToken: 'sess_live_8832c2d',
      analysisVersion: 'KisanDrishti Hybrid CV + Gemini v3.2',
      hasOptionalSheetUsed: false,
    },
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=1200&q=80',
    photos: {
      main: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=1200&q=80',
      closeUp: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=1200&q=80',
    },
    stats: {
      brokenPercent: 2.1,
      brokenCount: 9,
      discoloredPercent: 3.4,
      discoloredCount: 15,
      foreignObjectCount: 1,
      foreignObjectPercent: 0.2,
      visibleDamagePercent: 0.7,
      visibleDamageCount: 3,
      abnormalAppearanceCount: 0,
      sampleCoveragePercent: 92,
      captureQualityScore: 95,
      approximateAverageLengthMm: 1.8,
      opticalColorDistribution: 'Deep Brown-Black (Melanin) — 90% Optical Uniformity',
      totalObjects: 440,
      totalFlaggedObservations: 3,
      soundGrainRatePercent: 93.6,
    },
    detections: [
      {
        id: 1,
        category: 'discolored_shriveled',
        categoryLabel: 'Immature Green / Shriveled Seed',
        status: 'OBSERVED',
        confidence: 0.93,
        xPercent: 41.2,
        yPercent: 38.5,
        widthPercent: 2.8,
        heightPercent: 3.0,
        findingTitle: 'Discolored Mustard: Chlorophyll Retention',
        visualEvidence: 'Mustard seed with retained green chlorophyll coat instead of mature black-brown.',
        visualReasoning: 'Color temperature shows high green spectrum (520nm) vs melanin baseline.',
        estimatedSizeMm: 1.4,
        isHighPriorityAnomaly: true,
        colorHex: '#C2410C',
        photoSource: 'main',
      },
    ],
    matrixRows: [
      {
        id: 'mat-1',
        parameter: 'Visible Discoloration',
        categoryGroup: 'OBSERVED VISUAL EVIDENCE',
        result: '3.4% (15 items observed)',
        status: 'OBSERVED',
        method: 'Chromatic Dispersion',
        confidence: 'High',
        note: 'Immature green seeds observed in captured sample.',
      },
      {
        id: 'mat-unver-1',
        parameter: 'Oil Content (%)',
        categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
        result: 'Not tested (Requires solvent extraction or NMR)',
        status: 'UNVERIFIED',
        method: 'N/A',
        confidence: 'N/A',
        note: 'KisanDrishti does not test chemical oil percentage.',
      },
    ],
    explanations: [
      {
        finding: 'Immature Green Mustard Seed (#1)',
        visualEvidence: 'Green seed at coordinates (41.2%, 38.5%).',
        visualReasoning: 'Premature harvest indicator. Chlorophyll breakdown incomplete.',
        status: 'OBSERVED VISUAL EVIDENCE',
        limitation: 'Visual seed coat color only. Does not measure free fatty acid value.',
        markerId: 1,
      },
    ],
    cryptographicHash: 'e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2',
    isDemo: true,
    isConfidenceSufficient: true,
    shareCount: 1,
    verifiedAt: '2026-09-11T11:35:00.000Z',
  },
];
