import type { DetectionMarker, AuditRecord, EvidenceMatrixRow, GeminiExplanation } from '@/types/evidence';

export const DEMO_WHEAT_DETECTIONS: DetectionMarker[] = [
  {
    id: 1,
    category: 'foreign_object',
    categoryLabel: 'Foreign Object (Inorganic Gravel)',
    status: 'OBSERVED',
    confidence: 0.98,
    xPercent: 28.5,
    yPercent: 34.2,
    widthPercent: 4.2,
    heightPercent: 4.8,
    findingTitle: 'Foreign Object: Silica / Stone Fragment',
    visualEvidence: 'Dark crystalline, non-organic angular fragment with 0% grain contour agreement. High optical density and sharp edge reflectance.',
    visualReasoning: 'Contrast differential exceeding 75% compared to baseline wheat grain matrix. Geometry exhibits jagged non-biological cleavage planes.',
    estimatedSizeMm: 3.4,
    isHighPriorityAnomaly: true,
    colorHex: '#DC2626',
  },
  {
    id: 2,
    category: 'foreign_object',
    categoryLabel: 'Foreign Object (Weed Seed)',
    status: 'OBSERVED',
    confidence: 0.94,
    xPercent: 72.1,
    yPercent: 61.8,
    widthPercent: 3.5,
    heightPercent: 3.8,
    findingTitle: 'Foreign Object: Wild Black Weed Seed Candidate',
    visualEvidence: 'Small spherical black botanical seed (approx. 2.1mm) with micro-punctate seed coat distinct from Triticum aestivum kernel anatomy.',
    visualReasoning: 'Spherical aspect ratio (0.95) and deep melanin pigmentation indicate adventitious weed admixture (e.g. Chenopodium / Wild Oat).',
    estimatedSizeMm: 2.1,
    isHighPriorityAnomaly: true,
    colorHex: '#DC2626',
  },
  {
    id: 3,
    category: 'broken_grain',
    categoryLabel: 'Broken / Cleaved Grain Candidate',
    status: 'OBSERVED',
    confidence: 0.96,
    xPercent: 45.2,
    yPercent: 22.4,
    widthPercent: 3.8,
    heightPercent: 3.2,
    findingTitle: 'Broken Grain: Transverse Endosperm Cleavage',
    visualEvidence: 'Grain truncated at mid-section with exposed chalky starchy endosperm. Missing distal brush end.',
    visualReasoning: 'Length-to-width ratio of 1.15 vs standard 2.45 for intact wheat. Irregular fracture line with high chalk reflectance.',
    estimatedSizeMm: 3.2,
    isHighPriorityAnomaly: true,
    colorHex: '#D97706',
  },
  {
    id: 4,
    category: 'broken_grain',
    categoryLabel: 'Broken / Cleaved Grain Candidate',
    status: 'OBSERVED',
    confidence: 0.92,
    xPercent: 63.8,
    yPercent: 41.5,
    widthPercent: 3.4,
    heightPercent: 3.0,
    findingTitle: 'Broken Grain: Embryo Tip Fracture',
    visualEvidence: 'Germ end sheared off cleanly with exposed sub-aleurone tissue.',
    visualReasoning: 'Asymmetric contour loss corresponding to mechanical threshing damage.',
    estimatedSizeMm: 4.1,
    isHighPriorityAnomaly: true,
    colorHex: '#D97706',
  },
  {
    id: 5,
    category: 'discolored_shriveled',
    categoryLabel: 'Discoloration / Shriveled Candidate',
    status: 'OBSERVED',
    confidence: 0.89,
    xPercent: 38.0,
    yPercent: 55.6,
    widthPercent: 3.2,
    heightPercent: 4.5,
    findingTitle: 'Discolored / Shriveled Kernel',
    visualEvidence: 'Deep longitudinal wrinkles across pericarp with dull gray-brown hue (L* value 38 vs 62 normal).',
    visualReasoning: 'Thermal stress / premature desiccation pattern. Surface convolution depth exceeds 0.4mm.',
    estimatedSizeMm: 4.8,
    isHighPriorityAnomaly: true,
    colorHex: '#C2410C',
  },
  {
    id: 6,
    category: 'visible_physical_damage',
    categoryLabel: 'Visible Physical Damage Candidate',
    status: 'OBSERVED',
    confidence: 0.88,
    xPercent: 52.4,
    yPercent: 78.1,
    widthPercent: 3.6,
    heightPercent: 3.9,
    findingTitle: 'Visible Physical Pericarp Abrasion',
    visualEvidence: 'Surface bruising and pericarp abrasion on outer grain dorsal side.',
    visualReasoning: 'Abrasive rub marks typical of aggressive auger handling; seed coat fractured without full transverse split.',
    estimatedSizeMm: 5.6,
    isHighPriorityAnomaly: true,
    colorHex: '#B45309',
  },
  {
    id: 7,
    category: 'weevil_hole_candidate',
    categoryLabel: 'Bore Hole / Insect Damage Candidate',
    status: 'POSSIBLE',
    confidence: 0.84,
    xPercent: 18.2,
    yPercent: 67.4,
    widthPercent: 3.1,
    heightPercent: 3.4,
    findingTitle: 'Possible Insect Bore Hole Cavity',
    visualEvidence: 'Circular aperture (approx. 0.8mm) with dark internal shadowing on lateral flank.',
    visualReasoning: 'Optical shadowing suggests hollow entrance tunnel consistent with Sitophilus oryzae exit. Requires physical probe for 100% confirmation.',
    estimatedSizeMm: 5.2,
    isHighPriorityAnomaly: true,
    colorHex: '#B45309',
  },
  {
    id: 8,
    category: 'immature',
    categoryLabel: 'Immature / Green Tint Candidate',
    status: 'OBSERVED',
    confidence: 0.91,
    xPercent: 81.5,
    yPercent: 29.3,
    widthPercent: 3.0,
    heightPercent: 4.2,
    findingTitle: 'Immature Grain with Chlorophyll Residue',
    visualEvidence: 'Slight greenish hue shift (a* = -3.2) with reduced grain plumpness.',
    visualReasoning: 'Harvested prior to complete grain dry-down; remnant chlorophyll in aleurone layer.',
    estimatedSizeMm: 5.1,
    isHighPriorityAnomaly: false,
    colorHex: '#65A30D',
  },
];

export const DEMO_WHEAT_MATRIX_ROWS: EvidenceMatrixRow[] = [
  // OBSERVED VISUAL EVIDENCE
  {
    id: 'mat-1',
    parameter: 'Broken / Cleaved Candidates',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '6.4%',
    status: 'OBSERVED',
    method: 'Calibrated 2D Contour Aspect Ratio Analysis',
    confidence: 'High',
    note: 'Grains exhibiting cleaved endosperm or missing germ ends on 10x10cm optical grid.',
  },
  {
    id: 'mat-2',
    parameter: 'Foreign Object Candidates',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '2 items (1 Stone + 1 Weed Seed)',
    status: 'OBSERVED',
    method: 'Spectral & Geometric Contrast Differential',
    confidence: 'High',
    note: 'Inorganic silica stone (3.4mm) + wild weed seed (2.1mm) detected at spatial coordinates #1 and #2.',
  },
  {
    id: 'mat-3',
    parameter: 'Discoloration Candidates',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '1.8%',
    status: 'OBSERVED',
    method: 'Calibrated CIELAB Color Space Analysis',
    confidence: 'High',
    note: 'Kernels with noticeable luminance drop (L* < 42) and deep pericarp shriveling.',
  },
  {
    id: 'mat-4',
    parameter: 'Visible Physical Damage',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '1.2%',
    status: 'OBSERVED',
    method: 'Surface Texture & Edge Gradient Extraction',
    confidence: 'Medium',
    note: 'External mechanical scuffs and pericarp tears from post-harvest handling.',
  },
  {
    id: 'mat-5',
    parameter: 'Approximate Grain Length',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '6.8 ± 0.4 mm',
    status: 'OBSERVED',
    method: '10cm × 10cm Grid Metric Tick Calibration',
    confidence: 'High',
    note: 'Calibrated against 1mm millimeter boundary fiducial ticks on A4 sheet.',
  },
  {
    id: 'mat-6',
    parameter: 'Color Spectral Uniformity',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: 'Amber Golden (580nm) — 91% Uniform',
    status: 'OBSERVED',
    method: 'Optical Color Patch Comparative Histogram',
    confidence: 'High',
    note: 'Measured against RGB/CMYK standard swatches on calibration sheet.',
  },
  {
    id: 'mat-7',
    parameter: 'Sample Grid Coverage',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '94% (Even Dispersion)',
    status: 'OBSERVED',
    method: 'Spatial Area Occupancy Calculation',
    confidence: 'High',
    note: 'Sample is evenly spread across 100 cm² without dense stacking clusters.',
  },
  {
    id: 'mat-8',
    parameter: 'Capture Optical Quality',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '96% (540 Lux • 1.2° Tilt)',
    status: 'OBSERVED',
    method: 'Hardware Sensor & Fiducial Geometry Lock',
    confidence: 'High',
    note: 'All 4 fiducial corners locked; lighting illumination above 500 Lux threshold.',
  },
  {
    id: 'mat-9',
    parameter: 'Insect Bore Hole Cavity Candidate',
    categoryGroup: 'POSSIBLE VISUAL EVIDENCE',
    result: '1 Candidate Observed',
    status: 'POSSIBLE',
    method: 'Shadow Cavity Gradient Detection',
    confidence: 'Medium',
    note: 'Visual depth cavity matches weevil bore profile; requires internal physical slice to confirm.',
  },

  // UNVERIFIED
  {
    id: 'mat-10',
    parameter: 'Moisture Content',
    categoryGroup: 'UNVERIFIED (Laboratory Only)',
    result: 'Not tested',
    status: 'UNVERIFIED',
    method: 'Requires Calibrated Dielectric Moisture Meter',
    confidence: 'N/A',
    note: 'Surface photography cannot measure internal water activity or moisture percentage.',
  },
  {
    id: 'mat-11',
    parameter: 'Protein Content',
    categoryGroup: 'UNVERIFIED (Laboratory Only)',
    result: 'Not tested',
    status: 'UNVERIFIED',
    method: 'Requires NIR / Dumas Combustion Analyzer',
    confidence: 'N/A',
    note: 'Optical images cannot deduce crude protein or amino acid composition.',
  },
  {
    id: 'mat-12',
    parameter: 'Chemical Composition & Pesticide Residue',
    categoryGroup: 'UNVERIFIED (Laboratory Only)',
    result: 'Not tested',
    status: 'UNVERIFIED',
    method: 'Requires GC-MS / LC-MS Chemical Chromatography',
    confidence: 'N/A',
    note: 'Chemical residues leave no visible macroscopic signature on grain surfaces.',
  },
  {
    id: 'mat-13',
    parameter: 'Internal Fungal Contamination',
    categoryGroup: 'UNVERIFIED (Laboratory Only)',
    result: 'Not verified',
    status: 'UNVERIFIED',
    method: 'Requires Laboratory Incubation & Mycotoxin Assay',
    confidence: 'N/A',
    note: 'Endophytic fungal hyphae cannot be confirmed through non-destructive surface imaging.',
  },
  {
    id: 'mat-14',
    parameter: 'Gluten Index / Falling Number',
    categoryGroup: 'UNVERIFIED (Laboratory Only)',
    result: 'Not tested',
    status: 'UNVERIFIED',
    method: 'Requires Hagberg Perten Falling Number Apparatus',
    confidence: 'N/A',
    note: 'Enzymatic alpha-amylase activity cannot be determined visually.',
  },
];

export const DEMO_WHEAT_EXPLANATIONS: GeminiExplanation[] = [
  {
    finding: 'Foreign Inorganic Stone Fragment (3.4 mm)',
    visualEvidence: 'Located at normalized coordinates X: 28.5%, Y: 34.2% on 10x10cm calibration sheet. Angular silica geometry with zero biological grain symmetry.',
    visualReasoning: 'The optical density and specular reflectance profile diverge significantly from wheat kernel pericarp. High-contrast edge gradients confirm non-organic foreign matter.',
    status: 'OBSERVED VISUAL EVIDENCE',
    limitation: 'Identifies surface physical presence only. Cannot determine exact mineral hardness or geological origin.',
    markerId: 1,
  },
  {
    finding: 'Broken & Fractured Grain Cleavages (6.4% of sample)',
    visualEvidence: 'Flagged at coordinates #3 (X: 45.2%, Y: 22.4%) and #4 (X: 63.8%, Y: 41.5%). Exposed starchy white endosperm with jagged fracture borders.',
    visualReasoning: 'Geometric aspect ratio falls below 1.5 (normal intact kernel = 2.4 to 2.8). White chalky interior exposed to optical sensor with sharp reflectance step.',
    status: 'OBSERVED VISUAL EVIDENCE',
    limitation: 'Identifies macroscopic physical fractures. Cannot distinguish between mechanical threshing damage vs thermal stress cracks.',
    markerId: 3,
  },
  {
    finding: 'Discolored & Shriveled Grain Candidates (1.8% of sample)',
    visualEvidence: 'Flagged at coordinate #5 (X: 38.0%, Y: 55.6%). Severe longitudinal wrinkles with darkened hue (L* value 38 vs 62 baseline).',
    visualReasoning: 'Convoluted surface curvature indicates incomplete grain filling or early heat stress during physiological maturity.',
    status: 'OBSERVED VISUAL EVIDENCE',
    limitation: 'Observes surface contour and pigmentation. Cannot establish internal moisture or germination viability without lab testing.',
    markerId: 5,
  },
];

export const DEMO_WHEAT_AUDIT: AuditRecord = {
  id: 'KD-2026-WHT-8902',
  metadata: {
    auditId: 'KD-2026-WHT-8902',
    lotId: 'LOT-PB-2026-0419',
    crop: 'Wheat',
    variety: 'Sharbati HD-2967',
    location: 'Khanna Mandi, Ludhiana, Punjab',
    buyerRef: 'PUNJAB-GRAIN-TRADER-99',
    sampleSizeGrams: 250,
    captureTimestamp: '2026-09-13T09:45:00.000Z',
    deviceInfo: 'KisanDrishti Optical Standard v2.4 (Sony IMX686 64MP Sensor, F/1.8)',
    sessionToken: 'kd_sess_wht_8902_canonical_std',
    analysisVersion: 'KD-HybridEngine-v3.2',
  },
  imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=1200&q=80',
  stats: {
    brokenPercent: 6.4,
    brokenCount: 26,
    discoloredPercent: 1.8,
    discoloredCount: 8,
    foreignObjectCount: 2,
    foreignObjectPercent: 0.5,
    visibleDamagePercent: 1.2,
    visibleDamageCount: 5,
    sampleCoveragePercent: 94,
    captureQualityScore: 96,
    approximateAverageLengthMm: 6.8,
    opticalColorDistribution: 'Amber Golden (580nm) — 91% Uniform',
    totalObjects: 412,
    totalFlaggedObservations: 41,
    soundGrainRatePercent: 90.1,
  },
  detections: DEMO_WHEAT_DETECTIONS,
  matrixRows: DEMO_WHEAT_MATRIX_ROWS,
  explanations: DEMO_WHEAT_EXPLANATIONS,
  cryptographicHash: 'a7f4e912c3b845d06e210984f1a54b3c89201dfe6734a85209b1cd45ef890a12',
  isDemo: true,
  isConfidenceSufficient: true,
};

export const INITIAL_AUDIT_HISTORY: AuditRecord[] = [
  DEMO_WHEAT_AUDIT,
  {
    id: 'KD-2026-RIC-7714',
    metadata: {
      auditId: 'KD-2026-RIC-7714',
      lotId: 'LOT-HR-2026-1121',
      crop: 'Paddy (Rice)',
      variety: 'Pusa Basmati 1121',
      location: 'Karnal Mandi, Haryana',
      buyerRef: 'EXIM-RICE-CORP-401',
      sampleSizeGrams: 250,
      captureTimestamp: '2026-09-12T14:20:00.000Z',
      deviceInfo: 'KisanDrishti Optical Standard v2.4 (Sony IMX686 64MP Sensor, F/1.8)',
      sessionToken: 'kd_sess_ric_7714_std',
      analysisVersion: 'KD-HybridEngine-v3.2',
    },
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=80',
    stats: {
      brokenPercent: 4.2,
      brokenCount: 16,
      discoloredPercent: 1.1,
      discoloredCount: 4,
      foreignObjectCount: 1,
      foreignObjectPercent: 0.3,
      visibleDamagePercent: 0.8,
      visibleDamageCount: 3,
      sampleCoveragePercent: 96,
      captureQualityScore: 98,
      approximateAverageLengthMm: 8.4,
      opticalColorDistribution: 'Pearly Translucent (Off-white) — 94% Uniform',
      totalObjects: 380,
      totalFlaggedObservations: 24,
      soundGrainRatePercent: 93.8,
    },
    detections: DEMO_WHEAT_DETECTIONS.slice(0, 5),
    matrixRows: DEMO_WHEAT_MATRIX_ROWS.map(r => ({
      ...r,
      result: r.parameter === 'Broken / Cleaved Candidates' ? '4.2%' 
        : r.parameter === 'Foreign Object Candidates' ? '1 item (Weed Seed)'
        : r.parameter === 'Discoloration Candidates' ? '1.1%'
        : r.parameter === 'Approximate Grain Length' ? '8.4 ± 0.3 mm'
        : r.result,
    })),
    explanations: DEMO_WHEAT_EXPLANATIONS.slice(0, 2),
    cryptographicHash: '98e1a3b5c7d9e0f21436587098abcedf1234567890abcdef1234567890abcdef',
    isDemo: false,
    isConfidenceSufficient: true,
  },
  {
    id: 'KD-2026-MST-4029',
    metadata: {
      auditId: 'KD-2026-MST-4029',
      lotId: 'LOT-RJ-2026-092',
      crop: 'Mustard',
      variety: 'Brassica Pusa Mustard 25',
      location: 'Alwar Mandi, Rajasthan',
      buyerRef: 'RAJ-OIL-MILLS-12',
      sampleSizeGrams: 100,
      captureTimestamp: '2026-09-11T11:05:00.000Z',
      deviceInfo: 'KisanDrishti Optical Standard v2.4',
      sessionToken: 'kd_sess_mst_4029_std',
      analysisVersion: 'KD-HybridEngine-v3.2',
    },
    imageUrl: 'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=1200&q=80',
    stats: {
      brokenPercent: 2.1,
      brokenCount: 12,
      discoloredPercent: 3.4,
      discoloredCount: 19,
      foreignObjectCount: 3,
      foreignObjectPercent: 0.6,
      visibleDamagePercent: 1.5,
      visibleDamageCount: 8,
      sampleCoveragePercent: 91,
      captureQualityScore: 95,
      approximateAverageLengthMm: 1.8,
      opticalColorDistribution: 'Deep Brown-Black (Melanin) — 89% Uniform',
      totalObjects: 540,
      totalFlaggedObservations: 42,
      soundGrainRatePercent: 92.4,
    },
    detections: DEMO_WHEAT_DETECTIONS.slice(0, 4),
    matrixRows: DEMO_WHEAT_MATRIX_ROWS.map(r => ({
      ...r,
      result: r.parameter === 'Broken / Cleaved Candidates' ? '2.1%' 
        : r.parameter === 'Foreign Object Candidates' ? '3 items (Inorganic Gravel)'
        : r.parameter === 'Discoloration Candidates' ? '3.4%'
        : r.parameter === 'Approximate Grain Length' ? '1.8 ± 0.2 mm'
        : r.result,
    })),
    explanations: DEMO_WHEAT_EXPLANATIONS.slice(0, 2),
    cryptographicHash: '43f098abcedf1234567890abcdef98e1a3b5c7d9e0f2143658701234567890abcdef',
    isDemo: false,
    isConfidenceSufficient: true,
  },
];
