import type { DetectionMarker, AuditRecord, EvidenceMatrixRow, GeminiExplanation, CapturedPhotos, CropType } from '@/types/evidence';

export interface BenchmarkCommodityProfile {
  id: string;
  name: string;
  crop: CropType;
  variety: string;
  mandiLocation: string;
  lotId: string;
  badge: string;
  description: string;
  record: AuditRecord;
}

// 1. WHEAT BENCHMARK RECORD (Khanna Mandi, Punjab)
export const WHEAT_PHOTOS: CapturedPhotos = {
  main: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=1200&q=80',
  closeUp: 'https://images.unsplash.com/photo-1543257580-7269da773bf5?auto=format&fit=crop&w=1200&q=80',
  context: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1200&q=80',
};

export const WHEAT_DETECTIONS: DetectionMarker[] = [
  {
    id: 1,
    category: 'foreign_object',
    categoryLabel: 'Foreign Material (Inorganic Gravel)',
    status: 'OBSERVED',
    confidence: 0.98,
    xPercent: 28.5,
    yPercent: 34.2,
    widthPercent: 4.2,
    heightPercent: 4.8,
    findingTitle: 'Foreign Material: Inorganic Silica / Stone Fragment',
    visualEvidence: 'Dark crystalline, non-organic angular fragment with 0% grain contour agreement. High optical density and sharp edge reflectance.',
    visualReasoning: 'Contrast differential exceeding 75% compared to baseline wheat grain matrix. Geometry exhibits jagged non-biological cleavage planes.',
    estimatedSizeMm: 3.4,
    isHighPriorityAnomaly: true,
    colorHex: '#DC2626',
    photoSource: 'main',
  },
  {
    id: 2,
    category: 'foreign_object',
    categoryLabel: 'Foreign Material (Wild Weed Seed)',
    status: 'OBSERVED',
    confidence: 0.94,
    xPercent: 72.1,
    yPercent: 61.8,
    widthPercent: 3.5,
    heightPercent: 3.8,
    findingTitle: 'Foreign Material: Wild Black Weed Seed Candidate',
    visualEvidence: 'Small spherical black botanical seed (approx. 2.1mm) with micro-punctate seed coat distinct from wheat kernel anatomy.',
    visualReasoning: 'Spherical aspect ratio (0.95) and deep melanin pigmentation indicate adventitious weed admixture (e.g. Wild Oat / Black Grass).',
    estimatedSizeMm: 2.1,
    isHighPriorityAnomaly: true,
    colorHex: '#DC2626',
    photoSource: 'closeUp',
  },
  {
    id: 3,
    category: 'broken_grain',
    categoryLabel: 'Broken / Damaged Grain',
    status: 'OBSERVED',
    confidence: 0.96,
    xPercent: 45.2,
    yPercent: 22.4,
    widthPercent: 3.8,
    heightPercent: 3.2,
    findingTitle: 'Broken Grain: Transverse Endosperm Cleavage',
    visualEvidence: 'Grain truncated at mid-section with exposed chalky starchy endosperm. Missing distal brush end.',
    visualReasoning: 'Length-to-width ratio of 1.15 vs standard 2.45 for intact wheat. Irregular fracture line with high chalk reflectance.',
    estimatedSizeMm: 3.2,
    isHighPriorityAnomaly: true,
    colorHex: '#D97706',
    photoSource: 'main',
  },
  {
    id: 4,
    category: 'broken_grain',
    categoryLabel: 'Broken / Damaged Grain',
    status: 'OBSERVED',
    confidence: 0.92,
    xPercent: 63.8,
    yPercent: 41.5,
    widthPercent: 3.4,
    heightPercent: 3.0,
    findingTitle: 'Broken Grain: Embryo Tip Fracture',
    visualEvidence: 'Germ end sheared off cleanly with exposed sub-aleurone tissue.',
    visualReasoning: 'Asymmetric contour loss corresponding to mechanical threshing damage.',
    estimatedSizeMm: 4.1,
    isHighPriorityAnomaly: true,
    colorHex: '#D97706',
    photoSource: 'closeUp',
  },
  {
    id: 5,
    category: 'discolored_shriveled',
    categoryLabel: 'Visible Discoloration / Shriveled Kernel',
    status: 'OBSERVED',
    confidence: 0.89,
    xPercent: 38.0,
    yPercent: 55.6,
    widthPercent: 3.2,
    heightPercent: 4.5,
    findingTitle: 'Discolored / Shriveled Kernel (Thermal Stress Candidate)',
    visualEvidence: 'Deep longitudinal wrinkles across pericarp with dull gray-brown hue (L* value 38 vs 62 normal).',
    visualReasoning: 'Severe surface convolution and chromatic shift indicating premature terminal heat stress during grain filling.',
    estimatedSizeMm: 4.8,
    isHighPriorityAnomaly: true,
    colorHex: '#C2410C',
    photoSource: 'closeUp',
  },
  {
    id: 6,
    category: 'visible_physical_damage',
    categoryLabel: 'Physical Surface Damage',
    status: 'OBSERVED',
    confidence: 0.88,
    xPercent: 52.4,
    yPercent: 78.1,
    widthPercent: 3.6,
    heightPercent: 3.9,
    findingTitle: 'Physical Surface Abrasion',
    visualEvidence: 'Surface bruising and pericarp abrasion on outer grain dorsal side.',
    visualReasoning: 'Abrasive friction marks typical of mechanical auger handling.',
    estimatedSizeMm: 5.6,
    isHighPriorityAnomaly: true,
    colorHex: '#B45309',
    photoSource: 'main',
  },
  {
    id: 7,
    category: 'abnormal_appearance',
    categoryLabel: 'Abnormal Appearance / Surface Cavity',
    status: 'POSSIBLE',
    confidence: 0.84,
    xPercent: 18.2,
    yPercent: 67.4,
    widthPercent: 3.1,
    heightPercent: 3.4,
    findingTitle: 'Abnormal Surface Cavity / Possible Bore Aperture',
    visualEvidence: 'Circular aperture (approx. 0.8mm) with dark internal shadowing on lateral flank.',
    visualReasoning: 'Optical shadowing indicates 2D cavity. Classified as POSSIBLE because external optics cannot verify internal penetration without destructive slicing.',
    estimatedSizeMm: 5.2,
    isHighPriorityAnomaly: true,
    colorHex: '#B45309',
    photoSource: 'main',
  },
];

export const WHEAT_MATRIX_ROWS: EvidenceMatrixRow[] = [
  {
    id: 'mat-1',
    parameter: 'Broken / Damaged Material',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '5.2% (18 grains observed)',
    status: 'OBSERVED',
    method: '2D Pixel Geometry & Cleavage Contour Analysis',
    confidence: 'High',
    note: 'Grains exhibiting cleaved endosperm or sheared germ ends visible in captured photos.',
  },
  {
    id: 'mat-2',
    parameter: 'Visible Foreign Material',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '2 items detected (0.6%)',
    status: 'OBSERVED',
    method: 'Spectral & Geometric Contrast Differential',
    confidence: 'High',
    note: 'Inorganic stone fragment and wild weed seed identified with non-wheat reflectance profile.',
  },
  {
    id: 'mat-3',
    parameter: 'Visible Discoloration',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '1.4% (5 grains observed)',
    status: 'OBSERVED',
    method: 'Pericarp Chromatic Dispersion Analysis',
    confidence: 'High',
    note: 'Shriveled and dull gray-brown kernels distinct from standard amber golden baseline.',
  },
  {
    id: 'mat-4',
    parameter: 'Physical Surface Damage',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '1.1% (4 grains observed)',
    status: 'OBSERVED',
    method: 'Surface Texture & Abrasion Detection',
    confidence: 'Medium',
    note: 'Dorsal abrasions and mechanical friction marks on grain pericarp.',
  },
  {
    id: 'mat-5',
    parameter: 'Abnormal Visual Appearance',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: '1 candidate observed (Cavity aperture)',
    status: 'POSSIBLE',
    method: '2D Aperture Shadowing',
    confidence: 'Medium',
    note: 'Surface bore aperture visible; internal verification requires manual inspection.',
  },
  {
    id: 'mat-6',
    parameter: 'Capture Quality Gate Status',
    categoryGroup: 'OBSERVED VISUAL EVIDENCE',
    result: 'PASSED (96% Quality Score)',
    status: 'OBSERVED',
    method: '8-Parameter Pre-Validation CV Pipeline',
    confidence: 'High',
    note: 'Passed sharpness, lighting, framing, glare, shadow, and visibility checks.',
  },
  {
    id: 'mat-unver-1',
    parameter: 'Moisture Percentage',
    categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
    result: 'Not tested (Requires certified dielectric / oven moisture meter)',
    status: 'UNVERIFIED',
    method: 'N/A — Not Accessible via Smartphone Photography',
    confidence: 'N/A',
    note: 'KisanDrishti does not test chemical moisture. Do not infer moisture from visual color alone.',
  },
  {
    id: 'mat-unver-2',
    parameter: 'Protein / Gluten Content',
    categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
    result: 'Not tested (Requires NIR spectrometer or Kjeldahl chemical titration)',
    status: 'UNVERIFIED',
    method: 'N/A — Requires Laboratory Equipment',
    confidence: 'N/A',
    note: 'Biochemical protein cannot be derived from 2D smartphone images.',
  },
  {
    id: 'mat-unver-3',
    parameter: 'Chemical / Pesticide Residue',
    categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
    result: 'Not tested (Requires Chromatography / Mass Spectrometry)',
    status: 'UNVERIFIED',
    method: 'N/A — Requires Chemical Assay',
    confidence: 'N/A',
    note: 'Invisible micro-contaminants cannot be visually verified.',
  },
  {
    id: 'mat-unver-4',
    parameter: 'Internal Kernel Defects',
    categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
    result: 'Not verified (Requires X-ray or destructive slicing)',
    status: 'UNVERIFIED',
    method: 'N/A — Surface Photography Only',
    confidence: 'N/A',
    note: 'Surface observations do not prove absence of internal hidden larval development.',
  },
  {
    id: 'mat-unver-5',
    parameter: 'Final Price / Rupee Deduction',
    categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
    result: 'NOT CALCULATED (KisanDrishti does not decide value)',
    status: 'UNVERIFIED',
    method: 'N/A — Commercial Mandate',
    confidence: 'N/A',
    note: 'KisanDrishti does not calculate price cuts or enforce trade deductions.',
  },
];

export const WHEAT_EXPLANATIONS: GeminiExplanation[] = [
  {
    finding: 'Foreign Material: Inorganic Mineral Fragment (#1)',
    visualEvidence: 'Non-grain angular dark silhouette at coordinates (28.5%, 34.2%). Zero agreement with biological seed pericarp geometry.',
    visualReasoning: 'High optical density with sharp cleavage planes. Pixel intensity variance across RGB channels indicates non-organic crystalline mineral matter.',
    status: 'OBSERVED VISUAL EVIDENCE',
    limitation: 'Identifies surface foreign object in the captured sample only. Does not quantify total bulk foreign matter by weight across the entire truckload.',
    markerId: 1,
  },
  {
    finding: 'Transverse Endosperm Cleavage in Broken Grain (#3)',
    visualEvidence: 'Truncated grain contour with exposed white starchy endosperm at coordinates (45.2%, 22.4%). Distal brush end missing.',
    visualReasoning: 'Length-to-width ratio of 1.15 is significantly below standard intact wheat kernel morphology (2.45). High specular reflectance from fractured starch granules.',
    status: 'OBSERVED VISUAL EVIDENCE',
    limitation: 'Describes observable 2D surface fragmentation. Does not measure internal micro-fissuring.',
    markerId: 3,
  },
  {
    finding: 'Visible Discoloration & Thermal Desiccation (#5)',
    visualEvidence: 'Deep longitudinal wrinkles and dull gray-brown hue at coordinates (38.0%, 55.6%).',
    visualReasoning: 'L* luminosity value is 38 (normal baseline 62). Wrinkle convolution frequency indicates thermal stress during maturation.',
    status: 'OBSERVED VISUAL EVIDENCE',
    limitation: 'Visual discoloration only. Does not measure grain hardness or baking quality.',
    markerId: 5,
  },
  {
    finding: 'Abnormal Appearance: Possible Bore Aperture (#7)',
    visualEvidence: 'Circular dark aperture (approx. 0.8mm) with internal shadowing at coordinates (18.2%, 67.4%).',
    visualReasoning: '2D optical shadow suggests cavity depth. Classified as POSSIBLE because external optics cannot verify if cavity penetrates the full endosperm without destructive slicing.',
    status: 'POSSIBLE INTERPRETATION',
    limitation: 'Requires manual probe or physical inspection to confirm whether active larvae exist inside.',
    markerId: 7,
  },
];

export const BENCHMARK_WHEAT_AUDIT: AuditRecord = {
  id: 'EVD-2026-WHT-4029',
  metadata: {
    auditId: 'EVD-2026-WHT-4029',
    lotId: 'PB-KHN-2026-4029',
    crop: 'Wheat',
    variety: 'HD-3086 (Pusa Gautami)',
    location: 'Khanna Mandi, Yard Platform #4, Punjab',
    buyerRef: 'Markfed Procurement Ref #772',
    sampleDescription: 'Composite grab sample across 40 jute bags',
    captureTimestamp: '2026-09-13T06:45:00.000Z',
    deviceInfo: 'Standard Smartphone Rear Camera (12MP f/1.8)',
    sessionToken: 'sess_wht_khanna_772a',
    analysisVersion: 'KisanDrishti Hybrid CV + Gemini v3.2',
    hasOptionalSheetUsed: false,
  },
  imageUrl: WHEAT_PHOTOS.main,
  photos: WHEAT_PHOTOS,
  stats: {
    brokenPercent: 5.2,
    brokenCount: 18,
    discoloredPercent: 1.4,
    discoloredCount: 5,
    foreignObjectCount: 2,
    foreignObjectPercent: 0.6,
    visibleDamagePercent: 1.1,
    visibleDamageCount: 4,
    abnormalAppearanceCount: 1,
    sampleCoveragePercent: 94,
    captureQualityScore: 96,
    approximateAverageLengthMm: 6.8,
    opticalColorDistribution: 'Amber Golden (580nm) — 91% Optical Uniformity',
    totalObjects: 346,
    totalFlaggedObservations: 7,
    soundGrainRatePercent: 91.7,
  },
  qualityGate: {
    passed: true,
    score: 96,
    checks: {
      blur: { id: 'chk-blur', name: 'Sharpness', passed: true, detail: 'Grain contours sharply focused.', tip: 'Optimal focus' },
      shadows: { id: 'chk-shadows', name: 'Shadows', passed: true, detail: 'Minimal diffuse shadow.', tip: 'Even illumination' },
      lighting: { id: 'chk-lighting', name: 'Lighting', passed: true, detail: 'Daylight 550 Lux equivalent.', tip: 'High dynamic range' },
      glare: { id: 'chk-glare', name: 'Glare', passed: true, detail: 'Zero specular hot spots.', tip: 'Diffuse lighting' },
      framing: { id: 'chk-framing', name: 'Framing', passed: true, detail: 'Sample well centered in frame.', tip: 'Optimal framing' },
      sampleVisibility: { id: 'chk-vis', name: 'Visibility', passed: true, detail: 'High optical contrast.', tip: 'Clear separation' },
      overlap: { id: 'chk-over', name: 'Overlap', passed: true, detail: 'Macro close-up and context established.', tip: 'Multi-angle check' },
      resolution: { id: 'chk-res', name: 'Resolution', passed: true, detail: '1080p+ sub-millimeter features.', tip: 'Sufficient sensor' },
    },
    failureReasons: [],
    correctiveGuidance: [],
  },
  detections: WHEAT_DETECTIONS,
  matrixRows: WHEAT_MATRIX_ROWS,
  explanations: WHEAT_EXPLANATIONS,
  cryptographicHash: '8f7a6b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a',
  isConfidenceSufficient: true,
  shareCount: 12,
};

// 2. BASMATI PADDY (RICE) BENCHMARK RECORD (Karnal Mandi, Haryana)
export const PADDY_PHOTOS: CapturedPhotos = {
  main: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=80',
  closeUp: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=1200&q=80',
  context: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1200&q=80',
};

export const PADDY_DETECTIONS: DetectionMarker[] = [
  {
    id: 1,
    category: 'broken_grain',
    categoryLabel: 'Broken / Damaged Paddy Grain',
    status: 'OBSERVED',
    confidence: 0.97,
    xPercent: 32.4,
    yPercent: 28.6,
    widthPercent: 4.0,
    heightPercent: 3.5,
    findingTitle: 'Broken Paddy: Chalky Transverse Fracture',
    visualEvidence: 'Elongated Basmati paddy grain sheared at mid-rib with exposed chalky white core.',
    visualReasoning: 'Aspect ratio 1.82 vs standard 3.25 for unbroken Basmati 1121. Cleavage line exhibits high starchy reflectance.',
    estimatedSizeMm: 4.2,
    isHighPriorityAnomaly: true,
    colorHex: '#D97706',
    photoSource: 'main',
  },
  {
    id: 2,
    category: 'discolored_shriveled',
    categoryLabel: 'Discolored / Immature Paddy',
    status: 'OBSERVED',
    confidence: 0.91,
    xPercent: 64.2,
    yPercent: 48.0,
    widthPercent: 3.6,
    heightPercent: 4.2,
    findingTitle: 'Immature / Greenish Husk Kernel',
    visualEvidence: 'Greenish chlorophyll pigmentation on paddy lemma/palea indicating premature harvest.',
    visualReasoning: 'Spectral band shift towards 520nm (green hue). Grain exhibits incomplete endosperm filling.',
    estimatedSizeMm: 6.8,
    isHighPriorityAnomaly: true,
    colorHex: '#C2410C',
    photoSource: 'closeUp',
  },
  {
    id: 3,
    category: 'foreign_object',
    categoryLabel: 'Foreign Material (Paddy Straw / Chaff)',
    status: 'OBSERVED',
    confidence: 0.95,
    xPercent: 48.0,
    yPercent: 70.2,
    widthPercent: 6.2,
    heightPercent: 2.5,
    findingTitle: 'Foreign Matter: Fibrous Paddy Straw Segment',
    visualEvidence: 'Elongated cellulosic hollow straw piece (approx. 9.8mm) distinct from filled grains.',
    visualReasoning: 'Hollow cylindrical geometry with longitudinal striations. Zero mass density in center.',
    estimatedSizeMm: 9.8,
    isHighPriorityAnomaly: true,
    colorHex: '#DC2626',
    photoSource: 'main',
  },
];

export const BENCHMARK_PADDY_AUDIT: AuditRecord = {
  id: 'EVD-2026-PAD-8104',
  metadata: {
    auditId: 'EVD-2026-PAD-8104',
    lotId: 'HR-KRN-2026-8104',
    crop: 'Paddy (Rice)',
    variety: 'Basmati PB-1121 (Export Grade)',
    location: 'Karnal Grain Market, Shed B, Haryana',
    buyerRef: 'KRBL Rice Export Trader Ref #902',
    sampleDescription: 'Representative probe sample across 60 bags',
    captureTimestamp: '2026-09-13T05:30:00.000Z',
    deviceInfo: 'Standard Smartphone Camera (12MP)',
    sessionToken: 'sess_paddy_karnal_8104',
    analysisVersion: 'KisanDrishti Hybrid CV + Gemini v3.2',
    hasOptionalSheetUsed: true,
  },
  imageUrl: PADDY_PHOTOS.main,
  photos: PADDY_PHOTOS,
  stats: {
    brokenPercent: 4.1,
    brokenCount: 14,
    discoloredPercent: 1.8,
    discoloredCount: 6,
    foreignObjectCount: 1,
    foreignObjectPercent: 0.3,
    visibleDamagePercent: 0.9,
    visibleDamageCount: 3,
    abnormalAppearanceCount: 0,
    sampleCoveragePercent: 95,
    captureQualityScore: 98,
    approximateAverageLengthMm: 8.4,
    opticalColorDistribution: 'Pearly Translucent / Golden Husk — 93% Uniformity',
    totalObjects: 341,
    totalFlaggedObservations: 3,
    soundGrainRatePercent: 92.9,
  },
  qualityGate: {
    passed: true,
    score: 98,
    checks: {
      blur: { id: 'chk-blur', name: 'Sharpness', passed: true, detail: 'Paddy awns and husk sharply focused.', tip: 'Optimal focus' },
      shadows: { id: 'chk-shadows', name: 'Shadows', passed: true, detail: 'Even diffuse light.', tip: 'No shadow' },
      lighting: { id: 'chk-lighting', name: 'Lighting', passed: true, detail: 'Optimal daylight 580 Lux.', tip: 'No glare' },
      glare: { id: 'chk-glare', name: 'Glare', passed: true, detail: 'Clean non-glare surface.', tip: 'Optimal' },
      framing: { id: 'chk-framing', name: 'Framing', passed: true, detail: 'Centered on alignment sheet.', tip: 'Aligned' },
      sampleVisibility: { id: 'chk-vis', name: 'Visibility', passed: true, detail: 'High contrast against sheet.', tip: 'Clear' },
      overlap: { id: 'chk-over', name: 'Overlap', passed: true, detail: 'Context and macro views verified.', tip: 'Good overlap' },
      resolution: { id: 'chk-res', name: 'Resolution', passed: true, detail: 'High 12MP capture resolution.', tip: 'Sharp' },
    },
    failureReasons: [],
    correctiveGuidance: [],
  },
  detections: PADDY_DETECTIONS,
  matrixRows: [
    {
      id: 'p-mat-1',
      parameter: 'Broken / Chalky Fragmented Paddy',
      categoryGroup: 'OBSERVED VISUAL EVIDENCE',
      result: '4.1% (14 grains observed)',
      status: 'OBSERVED',
      method: 'Aspect Ratio & Chalky Core Cleavage Detection',
      confidence: 'High',
      note: 'Sheared Basmati grains visible on high-res camera view.',
    },
    {
      id: 'p-mat-2',
      parameter: 'Visible Immature / Greenish Husk',
      categoryGroup: 'OBSERVED VISUAL EVIDENCE',
      result: '1.8% (6 grains observed)',
      status: 'OBSERVED',
      method: 'Chlorophyll Chromatic Shift Detection',
      confidence: 'High',
      note: 'Greenish tinge indicating premature paddy harvest.',
    },
    {
      id: 'p-mat-3',
      parameter: 'Foreign Material (Straw/Chaff)',
      categoryGroup: 'OBSERVED VISUAL EVIDENCE',
      result: '1 item detected (0.3%)',
      status: 'OBSERVED',
      method: 'Cylindrical Non-Grain Segmentation',
      confidence: 'High',
      note: 'Paddy straw segment identified.',
    },
    {
      id: 'p-mat-unver-1',
      parameter: 'Moisture Percentage',
      categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
      result: 'Not tested (Requires certified lab moisture meter)',
      status: 'UNVERIFIED',
      method: 'N/A — Not Accessible via Smartphone Camera',
      confidence: 'N/A',
      note: 'Moisture cannot be verified by 2D photography.',
    },
    {
      id: 'p-mat-unver-2',
      parameter: 'Commercial Milling Yield / Head Rice Recovery',
      categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
      result: 'Not tested (Requires lab sheller and polisher assay)',
      status: 'UNVERIFIED',
      method: 'N/A',
      confidence: 'N/A',
      note: 'Milling yield requires mechanical de-husking test.',
    },
  ],
  explanations: [
    {
      finding: 'Broken Basmati Grain with Chalky Cleavage (#1)',
      visualEvidence: 'Basmati grain truncated at mid-point at coordinates (32.4%, 28.6%).',
      visualReasoning: 'Length of 4.2mm is well below unbroken Basmati 1121 standard (8.4mm). High chalk reflectance on fractured surface.',
      status: 'OBSERVED VISUAL EVIDENCE',
      limitation: 'Reflects sample photo only; does not predict full lot milling yield.',
      markerId: 1,
    },
  ],
  cryptographicHash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
  isConfidenceSufficient: true,
  shareCount: 8,
};

// 3. MUSTARD BENCHMARK RECORD (Alwar Mandi, Rajasthan)
export const MUSTARD_PHOTOS: CapturedPhotos = {
  main: 'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=1200&q=80',
  closeUp: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=1200&q=80',
  context: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1200&q=80',
};

export const MUSTARD_DETECTIONS: DetectionMarker[] = [
  {
    id: 1,
    category: 'broken_grain',
    categoryLabel: 'Crushed / Split Mustard Seed',
    status: 'OBSERVED',
    confidence: 0.96,
    xPercent: 41.2,
    yPercent: 33.8,
    widthPercent: 2.8,
    heightPercent: 2.8,
    findingTitle: 'Crushed / Split Mustard Seed with Exposed Yellow Cotyledon',
    visualEvidence: 'Ruptured dark melanin seed coat with exposed bright yellow internal cotyledon.',
    visualReasoning: 'Optical perimeter loss. Yellow cotyledon contrast against dark spherical coat.',
    estimatedSizeMm: 1.7,
    isHighPriorityAnomaly: true,
    colorHex: '#D97706',
    photoSource: 'main',
  },
  {
    id: 2,
    category: 'foreign_object',
    categoryLabel: 'Foreign Material (Fine Sand / Soil Clod)',
    status: 'OBSERVED',
    confidence: 0.93,
    xPercent: 68.5,
    yPercent: 57.2,
    widthPercent: 3.2,
    heightPercent: 3.0,
    findingTitle: 'Inorganic Soil Pellet Candidate',
    visualEvidence: 'Irregular earthy aggregate (approx. 2.4mm) with high matte surface roughness.',
    visualReasoning: 'Non-spherical rough particle with earthy chromatic profile distinct from brassica seeds.',
    estimatedSizeMm: 2.4,
    isHighPriorityAnomaly: true,
    colorHex: '#DC2626',
    photoSource: 'closeUp',
  },
];

export const BENCHMARK_MUSTARD_AUDIT: AuditRecord = {
  id: 'EVD-2026-MST-2291',
  metadata: {
    auditId: 'EVD-2026-MST-2291',
    lotId: 'RJ-ALW-2026-2291',
    crop: 'Mustard',
    variety: 'Pusa Bold (Black Mustard)',
    location: 'Alwar APMC Mandi, Yard Block 2, Rajasthan',
    buyerRef: 'Adani Wilmar Oil Mill Ref #304',
    sampleDescription: 'Random grab sample from 25 gunny bags',
    captureTimestamp: '2026-09-13T04:15:00.000Z',
    deviceInfo: 'Standard Smartphone Camera (12MP)',
    sessionToken: 'sess_mustard_alwar_2291',
    analysisVersion: 'KisanDrishti Hybrid CV + Gemini v3.2',
    hasOptionalSheetUsed: false,
  },
  imageUrl: MUSTARD_PHOTOS.main,
  photos: MUSTARD_PHOTOS,
  stats: {
    brokenPercent: 3.8,
    brokenCount: 16,
    discoloredPercent: 1.2,
    discoloredCount: 5,
    foreignObjectCount: 1,
    foreignObjectPercent: 0.2,
    visibleDamagePercent: 0.7,
    visibleDamageCount: 3,
    abnormalAppearanceCount: 0,
    sampleCoveragePercent: 96,
    captureQualityScore: 95,
    approximateAverageLengthMm: 1.8,
    opticalColorDistribution: 'Deep Melanin Brown-Black — 90% Uniformity',
    totalObjects: 420,
    totalFlaggedObservations: 2,
    soundGrainRatePercent: 94.1,
  },
  qualityGate: {
    passed: true,
    score: 95,
    checks: {
      blur: { id: 'chk-blur', name: 'Sharpness', passed: true, detail: 'Spherical micro-seeds resolved.', tip: 'Focused' },
      shadows: { id: 'chk-shadows', name: 'Shadows', passed: true, detail: 'Even daylight spread.', tip: 'No harsh shadow' },
      lighting: { id: 'chk-lighting', name: 'Lighting', passed: true, detail: 'Adequate diffuse light.', tip: 'Good' },
      glare: { id: 'chk-glare', name: 'Glare', passed: true, detail: 'No specular reflection.', tip: 'Clear' },
      framing: { id: 'chk-framing', name: 'Framing', passed: true, detail: 'Centered seed cluster.', tip: 'Framed' },
      sampleVisibility: { id: 'chk-vis', name: 'Visibility', passed: true, detail: 'High contrast against light background.', tip: 'Clear' },
      overlap: { id: 'chk-over', name: 'Overlap', passed: true, detail: 'Macro close-up and overall views verified.', tip: 'Overlap ok' },
      resolution: { id: 'chk-res', name: 'Resolution', passed: true, detail: 'High resolution sub-millimeter optics.', tip: 'Sharp' },
    },
    failureReasons: [],
    correctiveGuidance: [],
  },
  detections: MUSTARD_DETECTIONS,
  matrixRows: [
    {
      id: 'm-mat-1',
      parameter: 'Crushed / Split Mustard Seeds',
      categoryGroup: 'OBSERVED VISUAL EVIDENCE',
      result: '3.8% (16 seeds observed)',
      status: 'OBSERVED',
      method: 'Perimeter Rupture & Yellow Cotyledon Exposure',
      confidence: 'High',
      note: 'Split brassica seeds visible in macro photos.',
    },
    {
      id: 'm-mat-2',
      parameter: 'Foreign Material (Soil / Sand)',
      categoryGroup: 'OBSERVED VISUAL EVIDENCE',
      result: '1 item detected (0.2%)',
      status: 'OBSERVED',
      method: 'Earthy Chromatic & Texture Segmentation',
      confidence: 'High',
      note: 'Soil aggregate particle observed.',
    },
    {
      id: 'm-mat-unver-1',
      parameter: 'Oil Percentage / Erucic Acid Content',
      categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
      result: 'Not tested (Requires solvent extraction / NMR spectrometer)',
      status: 'UNVERIFIED',
      method: 'N/A — Chemical Extraction Only',
      confidence: 'N/A',
      note: 'Oil content cannot be derived from smartphone camera.',
    },
  ],
  explanations: [
    {
      finding: 'Crushed Mustard Seed with Exposed Yellow Cotyledon (#1)',
      visualEvidence: 'Split seed coat at coordinates (41.2%, 33.8%) showing yellow interior.',
      visualReasoning: 'Coat rupture confirms mechanical compression damage during harvesting or bagging.',
      status: 'OBSERVED VISUAL EVIDENCE',
      limitation: 'Describes observable sample seeds only; does not estimate whole truckload bulk density.',
      markerId: 1,
    },
  ],
  cryptographicHash: '3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d',
  isConfidenceSufficient: true,
  shareCount: 15,
};

// 4. SOYBEAN BENCHMARK RECORD (Indore Mandi, Madhya Pradesh)
export const SOYBEAN_PHOTOS: CapturedPhotos = {
  main: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&w=1200&q=80',
  closeUp: 'https://images.unsplash.com/photo-1543257580-7269da773bf5?auto=format&fit=crop&w=1200&q=80',
  context: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1200&q=80',
};

export const BENCHMARK_SOYBEAN_AUDIT: AuditRecord = {
  id: 'EVD-2026-SOY-6612',
  metadata: {
    auditId: 'EVD-2026-SOY-6612',
    lotId: 'MP-IND-2026-6612',
    crop: 'Soybean',
    variety: 'JS-9560 (Yellow Seed)',
    location: 'Indore APMC Mandi, Platform #12, Madhya Pradesh',
    buyerRef: 'Ruchi Soya Procurement Yard #45',
    sampleDescription: 'Representative grab sample from 30 bags',
    captureTimestamp: '2026-09-12T11:00:00.000Z',
    deviceInfo: 'Standard Smartphone Camera (12MP)',
    sessionToken: 'sess_soybean_indore_6612',
    analysisVersion: 'KisanDrishti Hybrid CV + Gemini v3.2',
    hasOptionalSheetUsed: false,
  },
  imageUrl: SOYBEAN_PHOTOS.main,
  photos: SOYBEAN_PHOTOS,
  stats: {
    brokenPercent: 4.6,
    brokenCount: 15,
    discoloredPercent: 2.1,
    discoloredCount: 7,
    foreignObjectCount: 2,
    foreignObjectPercent: 0.6,
    visibleDamagePercent: 1.2,
    visibleDamageCount: 4,
    abnormalAppearanceCount: 0,
    sampleCoveragePercent: 93,
    captureQualityScore: 97,
    approximateAverageLengthMm: 6.2,
    opticalColorDistribution: 'Creamy Pale Yellow (Buff) — 92% Uniformity',
    totalObjects: 328,
    totalFlaggedObservations: 4,
    soundGrainRatePercent: 91.5,
  },
  qualityGate: {
    passed: true,
    score: 97,
    checks: {
      blur: { id: 'chk-blur', name: 'Sharpness', passed: true, detail: 'Sharp hilum and cotyledon contours.', tip: 'Focused' },
      shadows: { id: 'chk-shadows', name: 'Shadows', passed: true, detail: 'Diffuse light.', tip: 'Clean' },
      lighting: { id: 'chk-lighting', name: 'Lighting', passed: true, detail: 'High dynamic range daylight.', tip: 'Optimal' },
      glare: { id: 'chk-glare', name: 'Glare', passed: true, detail: 'Zero specular reflection.', tip: 'Clean' },
      framing: { id: 'chk-framing', name: 'Framing', passed: true, detail: 'Centered sample.', tip: 'Framed' },
      sampleVisibility: { id: 'chk-vis', name: 'Visibility', passed: true, detail: 'High contrast separation.', tip: 'Clear' },
      overlap: { id: 'chk-over', name: 'Overlap', passed: true, detail: 'Macro and wide views verified.', tip: 'Multi-view' },
      resolution: { id: 'chk-res', name: 'Resolution', passed: true, detail: 'High resolution sensor.', tip: 'Sharp' },
    },
    failureReasons: [],
    correctiveGuidance: [],
  },
  detections: [
    {
      id: 1,
      category: 'broken_grain',
      categoryLabel: 'Split / Broken Soybean Cotyledon',
      status: 'OBSERVED',
      confidence: 0.95,
      xPercent: 35.8,
      yPercent: 42.1,
      widthPercent: 3.9,
      heightPercent: 3.4,
      findingTitle: 'Split Soybean Seed (Half Cotyledon)',
      visualEvidence: 'Soybean seed split cleanly along hilum suture with exposed inner embryo face.',
      visualReasoning: 'Hemi-spherical shape (aspect ratio 0.52 vs 0.98 normal). Loss of outer buff coat on split face.',
      estimatedSizeMm: 4.8,
      isHighPriorityAnomaly: true,
      colorHex: '#D97706',
      photoSource: 'main',
    },
  ],
  matrixRows: [
    {
      id: 's-mat-1',
      parameter: 'Split / Broken Soybean Cotyledons',
      categoryGroup: 'OBSERVED VISUAL EVIDENCE',
      result: '4.6% (15 seeds observed)',
      status: 'OBSERVED',
      method: 'Suture Cleavage & Hemi-spherical Geometry Detection',
      confidence: 'High',
      note: 'Mechanical split seeds observed in captured sample.',
    },
    {
      id: 's-mat-unver-1',
      parameter: 'Moisture Percentage & Oil Content',
      categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
      result: 'Not tested (Requires certified moisture meter / Soxhlet assay)',
      status: 'UNVERIFIED',
      method: 'N/A',
      confidence: 'N/A',
      note: 'Moisture and oil percentage are strictly unverified by camera.',
    },
  ],
  explanations: [
    {
      finding: 'Split Soybean Cotyledon (#1)',
      visualEvidence: 'Clean split half-seed at coordinates (35.8%, 42.1%).',
      visualReasoning: 'Indicates mechanical thresher impact.',
      status: 'OBSERVED VISUAL EVIDENCE',
      limitation: 'Visual observation of sample only.',
      markerId: 1,
    },
  ],
  cryptographicHash: '4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e',
  isConfidenceSufficient: true,
  shareCount: 6,
};

// 5. MAIZE BENCHMARK RECORD (Davangere APMC Mandi, Karnataka)
export const MAIZE_PHOTOS: CapturedPhotos = {
  main: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=1200&q=80',
  closeUp: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=1200&q=80',
  context: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1200&q=80',
};

export const BENCHMARK_MAIZE_AUDIT: AuditRecord = {
  id: 'EVD-2026-MAZ-9018',
  metadata: {
    auditId: 'EVD-2026-MAZ-9018',
    lotId: 'KA-DVG-2026-9018',
    crop: 'Maize',
    variety: 'HQPM-1 (Yellow Dent Corn)',
    location: 'Davangere APMC Mandi, Karnataka',
    buyerRef: 'Cargill Feed Plant Yard Ref #512',
    sampleDescription: 'Composite grab sample across 50 bags',
    captureTimestamp: '2026-09-12T09:30:00.000Z',
    deviceInfo: 'Standard Smartphone Camera (12MP)',
    sessionToken: 'sess_maize_davangere_9018',
    analysisVersion: 'KisanDrishti Hybrid CV + Gemini v3.2',
    hasOptionalSheetUsed: false,
  },
  imageUrl: MAIZE_PHOTOS.main,
  photos: MAIZE_PHOTOS,
  stats: {
    brokenPercent: 5.8,
    brokenCount: 17,
    discoloredPercent: 1.5,
    discoloredCount: 4,
    foreignObjectCount: 1,
    foreignObjectPercent: 0.3,
    visibleDamagePercent: 1.4,
    visibleDamageCount: 4,
    abnormalAppearanceCount: 1,
    sampleCoveragePercent: 94,
    captureQualityScore: 96,
    approximateAverageLengthMm: 9.5,
    opticalColorDistribution: 'Vibrant Amber / Golden Yellow — 94% Uniformity',
    totalObjects: 295,
    totalFlaggedObservations: 4,
    soundGrainRatePercent: 91.0,
  },
  qualityGate: {
    passed: true,
    score: 96,
    checks: {
      blur: { id: 'chk-blur', name: 'Sharpness', passed: true, detail: 'Corn crown and dent sharp.', tip: 'Focused' },
      shadows: { id: 'chk-shadows', name: 'Shadows', passed: true, detail: 'Even light spread.', tip: 'No shadow' },
      lighting: { id: 'chk-lighting', name: 'Lighting', passed: true, detail: 'Good daytime exposure.', tip: 'Optimal' },
      glare: { id: 'chk-glare', name: 'Glare', passed: true, detail: 'No specular wash.', tip: 'Clear' },
      framing: { id: 'chk-framing', name: 'Framing', passed: true, detail: 'Well-centered kernels.', tip: 'Framed' },
      sampleVisibility: { id: 'chk-vis', name: 'Visibility', passed: true, detail: 'High contrast.', tip: 'Separated' },
      overlap: { id: 'chk-over', name: 'Overlap', passed: true, detail: 'Multi-photo overlap verified.', tip: 'Good' },
      resolution: { id: 'chk-res', name: 'Resolution', passed: true, detail: 'Sub-millimeter resolution.', tip: 'Sharp' },
    },
    failureReasons: [],
    correctiveGuidance: [],
  },
  detections: [
    {
      id: 1,
      category: 'broken_grain',
      categoryLabel: 'Chipped Crown / Broken Maize Kernel',
      status: 'OBSERVED',
      confidence: 0.94,
      xPercent: 44.5,
      yPercent: 38.2,
      widthPercent: 4.8,
      heightPercent: 4.2,
      findingTitle: 'Chipped Maize Kernel: Crown Endosperm Cleavage',
      visualEvidence: 'Corn crown dent fractured with exposed white floury starch interior.',
      visualReasoning: 'Loss of apical dent curvature. High starch reflectance at fracture point.',
      estimatedSizeMm: 6.5,
      isHighPriorityAnomaly: true,
      colorHex: '#D97706',
      photoSource: 'main',
    },
  ],
  matrixRows: [
    {
      id: 'mz-mat-1',
      parameter: 'Chipped / Broken Corn Kernels',
      categoryGroup: 'OBSERVED VISUAL EVIDENCE',
      result: '5.8% (17 kernels observed)',
      status: 'OBSERVED',
      method: 'Crown Contour & Starch Exposure Detection',
      confidence: 'High',
      note: 'Mechanical shelling fracture observed.',
    },
    {
      id: 'mz-mat-unver-1',
      parameter: 'Aflatoxin / Mycotoxin / Moisture',
      categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
      result: 'Not tested (Requires ELISA / HPLC chemical assay & moisture meter)',
      status: 'UNVERIFIED',
      method: 'N/A — Biochemical Lab Assay Required',
      confidence: 'N/A',
      note: 'Microbial toxins cannot be confirmed by visible smartphone photography.',
    },
  ],
  explanations: [
    {
      finding: 'Chipped Corn Kernel (#1)',
      visualEvidence: 'Fractured crown dent at coordinates (44.5%, 38.2%).',
      visualReasoning: 'Shelling impact damage during mechanical harvesting.',
      status: 'OBSERVED VISUAL EVIDENCE',
      limitation: 'Sample inspection only.',
      markerId: 1,
    },
  ],
  cryptographicHash: '5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f',
  isConfidenceSufficient: true,
  shareCount: 9,
};

// 6. CHANA (CHICKPEA) BENCHMARK RECORD (Gulbarga APMC Mandi, Karnataka)
export const CHANA_PHOTOS: CapturedPhotos = {
  main: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=1200&q=80',
  closeUp: 'https://images.unsplash.com/photo-1543257580-7269da773bf5?auto=format&fit=crop&w=1200&q=80',
  context: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1200&q=80',
};

export const BENCHMARK_CHANA_AUDIT: AuditRecord = {
  id: 'EVD-2026-CHN-5501',
  metadata: {
    auditId: 'EVD-2026-CHN-5501',
    lotId: 'KA-GLB-2026-5501',
    crop: 'Chana (Chickpea)',
    variety: 'Desi Chana (JG-11)',
    location: 'Gulbarga APMC Mandi, Shed 5, Karnataka',
    buyerRef: 'Pulse Dal Mill Aggregator Ref #219',
    sampleDescription: 'Composite grab sample across 45 bags',
    captureTimestamp: '2026-09-11T14:20:00.000Z',
    deviceInfo: 'Standard Smartphone Camera (12MP)',
    sessionToken: 'sess_chana_gulbarga_5501',
    analysisVersion: 'KisanDrishti Hybrid CV + Gemini v3.2',
    hasOptionalSheetUsed: false,
  },
  imageUrl: CHANA_PHOTOS.main,
  photos: CHANA_PHOTOS,
  stats: {
    brokenPercent: 4.4,
    brokenCount: 13,
    discoloredPercent: 1.6,
    discoloredCount: 5,
    foreignObjectCount: 2,
    foreignObjectPercent: 0.7,
    visibleDamagePercent: 1.0,
    visibleDamageCount: 3,
    abnormalAppearanceCount: 1,
    sampleCoveragePercent: 95,
    captureQualityScore: 97,
    approximateAverageLengthMm: 7.5,
    opticalColorDistribution: 'Golden Brown / Tan — 91% Uniformity',
    totalObjects: 298,
    totalFlaggedObservations: 4,
    soundGrainRatePercent: 92.3,
  },
  qualityGate: {
    passed: true,
    score: 97,
    checks: {
      blur: { id: 'chk-blur', name: 'Sharpness', passed: true, detail: 'Sharp chickpea beaks and rough coat.', tip: 'Focused' },
      shadows: { id: 'chk-shadows', name: 'Shadows', passed: true, detail: 'Even light.', tip: 'No shadow' },
      lighting: { id: 'chk-lighting', name: 'Lighting', passed: true, detail: 'Good daylight.', tip: 'Optimal' },
      glare: { id: 'chk-glare', name: 'Glare', passed: true, detail: 'Zero glare.', tip: 'Clear' },
      framing: { id: 'chk-framing', name: 'Framing', passed: true, detail: 'Centered cluster.', tip: 'Framed' },
      sampleVisibility: { id: 'chk-vis', name: 'Visibility', passed: true, detail: 'High contrast.', tip: 'Clear' },
      overlap: { id: 'chk-over', name: 'Overlap', passed: true, detail: 'Multi-view overlap ok.', tip: 'Good' },
      resolution: { id: 'chk-res', name: 'Resolution', passed: true, detail: 'Sub-millimeter resolution.', tip: 'Sharp' },
    },
    failureReasons: [],
    correctiveGuidance: [],
  },
  detections: [
    {
      id: 1,
      category: 'broken_grain',
      categoryLabel: 'Split Cotyledon / Broken Chickpea',
      status: 'OBSERVED',
      confidence: 0.96,
      xPercent: 39.2,
      yPercent: 45.1,
      widthPercent: 4.4,
      heightPercent: 4.0,
      findingTitle: 'Broken Desi Chana: Sheared Beaked Tip',
      visualEvidence: 'Chickpea beak sheared off with exposed internal yellow cotyledon.',
      visualReasoning: 'Loss of characteristic angular beak geometry. Yellow cotyledon visible against brown seed coat.',
      estimatedSizeMm: 4.6,
      isHighPriorityAnomaly: true,
      colorHex: '#D97706',
      photoSource: 'main',
    },
  ],
  matrixRows: [
    {
      id: 'c-mat-1',
      parameter: 'Split / Broken Chickpeas',
      categoryGroup: 'OBSERVED VISUAL EVIDENCE',
      result: '4.4% (13 grains observed)',
      status: 'OBSERVED',
      method: 'Beak Fracture & Cotyledon Exposure Detection',
      confidence: 'High',
      note: 'Threshing breakage visible in captured photos.',
    },
    {
      id: 'c-mat-unver-1',
      parameter: 'Moisture Percentage & Internal Weevil Bore',
      categoryGroup: 'UNVERIFIED LABORATORY MEASUREMENTS',
      result: 'Not tested (Requires certified moisture meter / destructive dissection)',
      status: 'UNVERIFIED',
      method: 'N/A',
      confidence: 'N/A',
      note: 'Internal cavity larval existence requires manual probing or lab assay.',
    },
  ],
  explanations: [
    {
      finding: 'Broken Desi Chana Grain (#1)',
      visualEvidence: 'Sheared chickpea beak at coordinates (39.2%, 45.1%).',
      visualReasoning: 'Mechanical handling stress during pulse harvesting.',
      status: 'OBSERVED VISUAL EVIDENCE',
      limitation: 'Sample inspection only.',
      markerId: 1,
    },
  ],
  cryptographicHash: '6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a',
  isConfidenceSufficient: true,
  shareCount: 11,
};

// 6-COMMODITY BENCHMARK PROFILES FOR PRODUCTION SHOWCASE
export const BENCHMARK_COMMODITIES: BenchmarkCommodityProfile[] = [
  {
    id: 'wheat',
    name: 'Wheat (Gehun / Kanak)',
    crop: 'Wheat',
    variety: 'HD-3086 (Pusa Gautami)',
    mandiLocation: 'Khanna APMC Mandi, Punjab',
    lotId: 'PB-KHN-2026-4029',
    badge: 'North India Wheat Belt',
    description: 'High-volume mandi transaction record with localized mineral fragment and broken grain contours.',
    record: BENCHMARK_WHEAT_AUDIT,
  },
  {
    id: 'paddy',
    name: 'Basmati Paddy (Rice)',
    crop: 'Paddy (Rice)',
    variety: 'Basmati PB-1121 (Export Grade)',
    mandiLocation: 'Karnal Grain Market, Haryana',
    lotId: 'HR-KRN-2026-8104',
    badge: 'Export Basmati Belt',
    description: 'Premium aromatic paddy lot verified with chalky endosperm cleavage and paddy straw markers.',
    record: BENCHMARK_PADDY_AUDIT,
  },
  {
    id: 'mustard',
    name: 'Mustard (Sarson / Rai)',
    crop: 'Mustard',
    variety: 'Pusa Bold (Black Mustard)',
    mandiLocation: 'Alwar APMC Mandi, Rajasthan',
    lotId: 'RJ-ALW-2026-2291',
    badge: 'Rajasthan Oilseed Belt',
    description: 'Spherical micro-seed protocol with localized split seeds and yellow cotyledon exposure.',
    record: BENCHMARK_MUSTARD_AUDIT,
  },
  {
    id: 'soybean',
    name: 'Soybean (Pili Soy)',
    crop: 'Soybean',
    variety: 'JS-9560 (Yellow Seed)',
    mandiLocation: 'Indore APMC Mandi, Madhya Pradesh',
    lotId: 'MP-IND-2026-6612',
    badge: 'Central Oilseed Hub',
    description: 'Commercial pulse/oilseed transaction record featuring suture cleavage detection.',
    record: BENCHMARK_SOYBEAN_AUDIT,
  },
  {
    id: 'maize',
    name: 'Maize (Makka / Corn)',
    crop: 'Maize',
    variety: 'HQPM-1 (Yellow Dent Corn)',
    mandiLocation: 'Davangere APMC Mandi, Karnataka',
    lotId: 'KA-DVG-2026-9018',
    badge: 'South India Corn Belt',
    description: 'Industrial feed-grade maize lot with crown chipped endosperm detection and zero fabricated toxins.',
    record: BENCHMARK_MAIZE_AUDIT,
  },
  {
    id: 'chana',
    name: 'Chana (Desi Chickpea)',
    crop: 'Chana (Chickpea)',
    variety: 'Desi Chana (JG-11)',
    mandiLocation: 'Gulbarga APMC Mandi, Karnataka',
    lotId: 'KA-GLB-2026-5501',
    badge: 'Deccan Pulse Hub',
    description: 'Standardized pulse transaction record with beak shear analysis and strict lab disclaimers.',
    record: BENCHMARK_CHANA_AUDIT,
  },
];

export const INITIAL_AUDIT_HISTORY: AuditRecord[] = [
  BENCHMARK_WHEAT_AUDIT,
  BENCHMARK_PADDY_AUDIT,
  BENCHMARK_MUSTARD_AUDIT,
  BENCHMARK_SOYBEAN_AUDIT,
  BENCHMARK_MAIZE_AUDIT,
  BENCHMARK_CHANA_AUDIT,
];

// Helper to look up benchmark by ID
export function getBenchmarkCommodity(id: string): BenchmarkCommodityProfile {
  const match = BENCHMARK_COMMODITIES.find(c => c.id.toLowerCase() === id.toLowerCase() || c.crop.toLowerCase() === id.toLowerCase());
  return match || BENCHMARK_COMMODITIES[0];
}
